### PR TITLE
Add example YAML for two v14 devices connected via BLE

### PR DESCRIPTION
**Pull request by gyrex**

### CODE REVIEW

**Review by syssi — APPROVED** [review]
Thanks for your contribution!

**Comment by pilabcnc** [comment]
I am a newbie. What is "v14" device?

**Comment by syssi** [comment]
@pilabcnc It's the software/hardware version of the BMS.

**Comment by gyrex** [comment]
> I am a newbie. What is "v14" device?

They are the newer "PB" Inverter style BMSs which are hardware versions v14 & v15.

**Pull request merged**
