### PR TITLE
Add UART-TTL command support (write registers)

### PR DESCRIPTION
**Pull request by syssi**
See #341

```
substitutions:
  external_components_source: github://syssi/esphome-jk-bms@add-controls

external_components:
  - source: ${external_components_source}
    refresh: 0s
```

- [x] Handle short response frames

### CODE REVIEW

**Comment by jrventer** [comment]
Hi

Did a quick build but looks like it is not working. Below the logs. Did you put 100ms delay between the 0x5 and the write request as from below it seems there is no delay?
[09:09:26][D][switch:016]: 'esphome-web-f3d9c8 charging' Turning OFF.
[09:09:26][D][switch:055]: 'esphome-web-f3d9c8 charging': Sending state OFF
[09:09:26][D][uart_debug:158]: >>> "NW\x00\x14\x00\x00\x00\x00\x05\x02\x00\xB2\x00\x00\x00\x00\x00h\x00\x00\x01rNW\x00\x14\x00\x00\x00\x00\x02\x02\x00\xAB\x00\x00\x00\x00\x00h\x00\x00\x01h"
[09:09:30][D][switch:012]: 'esphome-web-f3d9c8 charging' Turning ON.
[09:09:30][D][switch:055]: 'esphome-web-f3d9c8 charging': Sending state ON
[09:09:30][D][uart_debug:158]: >>> "NW\x00\x14\x00\x00\x00\x00\x05\x02\x00\xB2\x00\x00\x00\x00\x00h\x00\x00\x01rNW\x00\x14\x00\x00\x00\x00\x02\x02\x00\xAB\x01\x00\x00\x00\x00h\x00\x00\x01i"

**Comment by jrventer** [comment]
@syssi also update the crc frame length to 18 as per the main thread.
frame[11] = address;  // register: 0x00 (read all registers), 0x8E...0xBF (holding registers)
  frame[12] = value;    // data
  frame[13] = 0x00;     // record number
  frame[14] = 0x00;     // record number
  frame[15] = 0x00;     // record number
  frame[16] = 0x00;     // record number
  frame[17] = 0x68;     // end sequence
  auto crc = chksum(frame, 17); <<<<<<<<<< should be 18

**Comment by syssi** [comment]
Fixed. Is the delay required? I would like to avoid delays as long as possible.

**Comment by jrventer** [comment]
> Fixed. Is the delay required? I would like to avoid delays as long as possible.

From the documentation they state it is required between requests but lets test without it with the checksum fixed.

**Comment by jrventer** [comment]
> Fixed. Is the delay required? I would like to avoid delays as long as possible.

Ok tested still not working likely would need some delay between the auth and write request.

**Comment by syssi** [comment]
I've added a `delay(150)` between the commands.

**Comment by jrventer** [comment]
> I've added a `delay(150)` between the commands.

Ok works now but see this in the logs "[jk_bms:056]: Invalid size (5) for JK BMS frame!" not sure why but will have to check. Also balancer switch not working looks like you not using the correct register.

Balancer Switch:
[10:58:54][D][uart_debug:158]: >>> "NW\x00\x14\x00\x00\x00\x00\x05\x02\x00\xB2\x00\x00\x00\x00\x00h\x00\x00\x01\xDANW\x00\x14\x00\x00\x00\x00\x02\x02\x00\x9D\x01\x00\x00\x00\x00h\x00\x00\x01\xC3"
[10:58:54][W][jk_bms:056]: Invalid size (5) for JK BMS frame!
[10:58:54][D][uart_debug:158]: <<< "NW\x00\x13\x00\x00\x00\x00\x02\x00\x01\x9D\x00\x00\x00\x00h\x00\x00\x01\xC0"
 Seems like you are using 0x9D but from the document it should be 9A for Active equalisation switch.

Below logs for charge and discharge that is working:
[10:57:06][D][switch:012]: 'esphome-web-f3d9c8 charging' Turning ON.
[10:57:07][D][switch:055]: 'esphome-web-f3d9c8 charging': Sending state ON
[10:57:07][D][uart_debug:158]: >>> "NW\x00\x14\x00\x00\x00\x00\x05\x02\x00\xB2\x00\x00\x00\x00\x00h\x00\x00\x01\xDANW\x00\x14\x00\x00\x00\x00\x02\x02\x00\xAB\x01\x00\x00\x00\x00h\x00\x00\x01\xD1"
[10:57:07][W][jk_bms:056]: Invalid size (5) for JK BMS frame!
[10:57:07][D][uart_debug:158]: <<< "NW\x00\x13\x00\x00\x00\x00\x02\x00\x01\xAB\x00\x00\x00\x00h\x00\x00\x01\xCE"
[10:57:09][D][switch:016]: 'esphome-web-f3d9c8 charging' Turning OFF.
[10:57:09][D][switch:055]: 'esphome-web-f3d9c8 charging': Sending state OFF
[10:57:09][D][uart_debug:158]: >>> "NW\x00\x14\x00\x00\x00\x00\x05\x02\x00\xB2\x00\x00\x00\x00\x00h\x00\x00\x01\xDANW\x00\x14\x00\x00\x00\x00\x02\x02\x00\xAB\x00\x00\x00\x00\x00h\x00\x00\x01\xD0"
[10:57:09][W][jk_bms:056]: Invalid size (5) for JK BMS frame!
[10:57:09][D][uart_debug:158]: <<< "NW\x00\x13\x00\x00\x00\x00\x02\x00\x01\xAB\x00\x00\x00\x00h\x00\x00\x01\xCE"
[10:57:12][D][switch:012]: 'esphome-web-f3d9c8 discharging' Turning ON.
[10:57:12][D][switch:055]: 'esphome-web-f3d9c8 discharging': Sending state ON
[10:57:12][D][uart_debug:158]: >>> "NW\x00\x14\x00\x00\x00\x00\x05\x02\x00\xB2\x00\x00\x00\x00\x00h\x00\x00\x01\xDANW\x00\x14\x00\x00\x00\x00\x02\x02\x00\xAC\x01\x00\x00\x00\x00h\x00\x00\x01\xD2"
[10:57:12][W][jk_bms:056]: Invalid size (5) for JK BMS frame!
[10:57:12][D][uart_debug:158]: <<< "NW\x00\x13\x00\x00\x00\x00\x02\x00\x01\xAC\x00\x00\x00\x00h\x00\x00\x01\xCF"
[10:57:14][D][switch:016]: 'esphome-web-f3d9c8 discharging' Turning OFF.
[10:57:14][D][switch:055]: 'esphome-web-f3d9c8 discharging': Sending state OFF
[10:57:14][D][uart_debug:158]: >>> "NW\x00\x14\x00\x00\x00\x00\x05\x02\x00\xB2\x00\x00\x00\x00\x00h\x00\x00\x01\xDANW\x00\x14\x00\x00\x00\x00\x02\x02\x00\xAC\x00\x00\x00\x00\x00h\x00\x00\x01\xD1"
[10:57:14][W][jk_bms:056]: Invalid size (5) for JK BMS frame!

**Comment by jrventer** [comment]
Had a quick look at seems like in jk_bms.cpp the registers from after 0x90 will need to checked and aligned with the latest documents. Hopefully not a difference for older version of the BMS that would need to be catered for.

Using this document as a reference:
https://github.com/NEEY-electronic/JK/blob/JK-BMS/BMS-RS485Communication%20protocol.pdf

**Comment by syssi** [comment]
Hmm... it looks like the registers has changed over time. Interesting.

**Comment by jrventer** [comment]
Ok also does not work but I have also now checked and looks like 0x9D was correct corresponding with example document:
https://github.com/NEEY-electronic/JK/blob/JK-BMS/Jikong-BMS-RS485-Communication%20example.pdf The protocol document is clearly older.

Difficult without the correct documentation. Will have to see why it did not want to write with 0x9D. Also confirmed the 0x9D changes when changing the switch via BLE app.

**Comment by syssi** [comment]
Could you try to identify the minimum required delay?

**Comment by jrventer** [comment]
Ok I have done further testing but cannot get the balancer switch to change. I think you will have to just do the charge and discharge switches for now which I believe is a huge improvement already. I will try and see what I can get out of JK further. If we can just get the code for bluetooth module we should be able to get this working quickly as that seem to have the best knowledge of the protocol of the BMS.

For the authentication you can also change the 0xB2 to 0x00 as it seems to be ignored.

For the delay between the auth and the write it appears to work with 10ms even I guess it depends on what the BMS microcontroller is busy with. My testing for this was using a lambda to build the frame for uart.write function in esphome config so might be handled slightly differently to the delay you adding at the lower level code side. I guess the best way to test would be to for you build and the modify the value and rebuild and test.

**Comment by jrventer** [comment]
After some further testing I will keep delay at 100ms.

**Comment by syssi** [comment]
@jrventer I've applied all suggestions! Thanks a lot for heavily testing. I've the chance today to test the code on a pretty old BMS firmware version. If it does work out of the box this is ready to get merged!

**Comment by syssi** [comment]
TODO: Handle short response frames

**Comment by syssi** [comment]
My BMS (JK-BD6A17S6P, hw 7.2, sw 7.1.0H) needs a pretty high delay around 200ms to accept authenticated write instructions. But it's working!! :-)

**Comment by jrventer** [comment]
@syssi Not sure if you are aware but JK actually list your project url right at the top of the document they ship with the BMS. I only noticed it recently as I did not really look at it before. So they basically acknowledge that the community have a better understanding on their communication interfaces. I suspect they got a 3rd party company to develop the BMS firmware and communication components thats why they are not able to easily access information on this topic.
image

**Comment by syssi** [comment]
We already celebrated this nice fact a year ago here: #132

**Comment by shvmm** [comment]
in the file:
components/jk_bms/switch/__init__.py

`from .. import CONF_JK_BMS_ID, JK_BMS_COMPONENT_SCHEMA, jk_bms_ns
from ..const import CONF_BALANCER, CONF_CHARGING, CONF_DISCHARGING`

I'm guessing the code for balancer switch included is like this:
`switch:
  - platform: jk_bms
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"
`

**Comment by syssi** [comment]
@LichtiMC the balancing switch cannot be controlled via the UART-TTL (GPS) protocol unfortunately.

**Pull request merged**
