### PR TITLE
Add Modbus support of the new range of JK BMS called JK-PB

### PR DESCRIPTION
**Pull request by syssi**
See #390

### CODE REVIEW

**Comment by txubelaxu** [comment]
See https://github.com/syssi/esphome-jk-bms/pull/464

**Comment by brycelarge** [comment]
Is there a wiring diagram I could use to test with?

**Comment by txubelaxu** [comment]
> Is there a wiring diagram I could use to test with?

https://github.com/syssi/esphome-jk-bms/issues/463#issuecomment-1973320806

**Comment by andersonray** [comment]
Thanks for the hard work adding this support! :) I have the JK-PB2A16S20P

Is this the config I should use if I only have one JK-PB BMS? I see  #464 for multiple

I don't see a `talk` pin defined in this config. This is still meant to use RS485 and connect to one of the battery comm ports? Can I use this style of RS485 to UART converter that doesn't need direction control? 
image

**Comment by txubelaxu** [comment]
Well, I have not tested that kind of UART to RS485 converters. Anyway,
* it should work with no talk_pin connected, as well as, no tx pin connected. Only RX pin for "listening mode"
* If you have only one bms it should be "master" (0x00 addresss), because it is the only way to "speak" into the RS485 internal network.

The "talk_pin" is used to ask for "board info" (frame type 3rd) to slaves acting as pseudo master. It has been impossible for me get that information from master (because it has 0x00 address and you cannot ask to that address in RS485 network from "another" master)

If you set the BMS with another address and you connect TX pin as well, in theory, the ESP should act as MASTER because in listening mode (the first mode that uses) it does not detect any master in the network. This way, ESP gets all the info (frame types: 1, 2 and 3) from that slave. Of course, I do not know what happens in the communication upstream (using CAN bus towards inverter...) You can test it

Good Luck!!!

**Comment by meccip** [comment]
I just test it esp-jk-bms.yaml (for BxAXXXXP bms) and is working on JKPB serries, connected on RS485port for inverter and select UART1 for 4G-GPS protocol (000)

@andersonray i use that board.

**Comment by andersonray** [comment]
> I just test it esp-jk-bms.yaml (for BxAXXSXXP bms) and is working on JKPB serries, connected on RS485port for inverter and select UART1 for 4G-GPS protocol (000)
> 
> @andersonray i use that board.
> 

@meccip Thanks for that info! I will definitely try that out. I did get the new battery bus listener config to work, but it does miss a few minor values. My inverter uses CAN, so the 485 inverter port is a good option.

**Pull request merged**
