### PR TITLE
Add charging and discharging power sensor

### PR DESCRIPTION
**Pull request by syssi**
```
sensor:
  - platform: jk_bms
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
```

@SeByDocKy FYI. You could use these new sensors instead of your sensor templates.

### CODE REVIEW

**Comment by SeByDocKy** [comment]
@syssi sounds great asap :). All are positive values ? (needed for the HA Energy panel). Other question... You pushed yesteday the switch version of the balancer/charger/discharger in addition of binary sensors. Are the switches now can control these actions ?

**Comment by syssi** [comment]
@SeByDocKy Yes. All values positive:

https://github.com/syssi/esphome-jk-bms/pull/69/files#diff-669c406eaff134c0b07174355c7c77eed6b8b81d2bd33db160bedb60d147267bR137-R138

The new "switch sensor": The switches cannot be controlled via the UART connection. This is the purpose of the new switches:

- `binary_sensor.balancer_switch` -> the switch position/state of the balancer switch at the android app
- `binary_sensor.balancer` -> Indicates the BMS is balancing at the moment
- `binary_sensor.charging_switch` -> the switch state of the charging switch at the android app
- `binary_sensor.charging` -> If some errors state (overvoltage/undervoltage) kicks in the `charging` sensor goes to `off` because of the protection. The `charging_switch` is still on.

**Comment by syssi** [comment]
@SeByDocKy Regarding the energy dashboard: I'm talking about `power` sensors (in W). I'm not talking about energy in Wh. If I remember correctly the energy dashboard requires total energy measurements in Wh (incoming/outgoing).

**Comment by SeByDocKy** [comment]
> @SeByDocKy Regarding the energy dashboard: I'm talking about `power` sensors (in W). I'm not talking about energy in Wh. If I remember correctly the energy dashboard requires total energy measurements in Wh (incoming/outgoing).

Yes exacts :)

**Comment by syssi** [comment]
@SeByDocKy Try to feed the [total_daily_energy component](https://esphome.io/components/sensor/total_daily_energy.html) with the new sensors (one per sensor). This should work out of the box!

**Comment by SeByDocKy** [comment]
> @SeByDocKy Try to feed the [total_daily_energy component](https://esphome.io/components/sensor/total_daily_energy.html) with the new sensors (one per sensor). This should work out of the box!

Yes I will test but i am sure at 99.99% it will work out of the box with your new builtin sensors :)

**Pull request merged**
